<?php
/**
 * @file
 * Contains gacsp.module.
 */

use Drupal\gacsp\AnalyticsEvents;
use Drupal\gacsp\Event\CollectEvent;

/**
 * Implements hook_page_attachments().
 */
function gacsp_page_attachments(array &$attachments) {

  /** @var CollectEvent $event */
  $event = \Drupal::service('event_dispatcher')
    ->dispatch(AnalyticsEvents::COLLECT, new CollectEvent());

  $attachments['#attached']['library'][] = 'gacsp/analytics';
  $attachments['#attached']['drupalSettings']['gacsp']['commands'] = $event->getDrupalSettingCommands();
}
