<?php
/**
 * @file
 * Contains gacsp.module.
 */

use Drupal\gacsp\AnalyticsCommand\Create;
use Drupal\gacsp\AnalyticsCommand\Pageview;
use Drupal\gacsp\AnalyticsCommand\RequirePlugin;

/**
 * Implements hook_page_attachments().
 */
function gacsp_page_attachments(array &$attachments) {

  /** @var \Drupal\gacsp\CommandRegistryService $command_registry */
  $command_registry = \Drupal::service('gacsp.command_registry');

  $config = \Drupal::configFactory()->get('gacsp.settings');
  if ($config->get('add_default_commands')) {
    if (($tracking_id = $config->get('tracking_id'))) {
      $command_registry->addItem(new Create($tracking_id));
    }
    if ($config->get('send_pageview')) {
      $command_registry->addItem(new Pageview());
    }
    if ($config->get('plugins.linkid')) {
      $command_registry->addItem(new RequirePlugin('linkid'));
    }
    if ($config->get('plugins.displayfeatures')) {
      $command_registry->addItem(new RequirePlugin('displayfeatures'));
    }
  }

  $attachments['#attached']['library'][] = 'gacsp/analytics';
  $attachments['#attached']['drupalSettings']['gacsp']['commands'] = $command_registry->getDrupalSettingCommands();
}
