# Schema file for the configuration files of the gacsp module.
gacsp.settings:
  type: config_object
  label:  'Google Analytics Settings'
  mapping:
    tracking_id:
      type: string
      label: 'Web Property Tracking ID'
    add_default_commands:
      type: boolean
      label: 'Add default analytics commands to registry'
