# Schema file for the configuration files of the gacsp module.
gascp.settings:
  type: config_object
  label:  'Google Analytics Settings'
  mapping:
    tracking_id:
      type: string
      label: 'Web Property Tracking ID'
